import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';



const Home: NextPage = () => {
  const playSound = () => {
    const audio = new Audio("./audio/toilet-flush-quite-aggressive.mp3");
    audio.play();
  };

  return (
    <div className=" ">
       
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="h-screen px-4 bg-[url('../pics/t.webp')] bg-no-repeat bg-center relative">
        <div className='flex justify-end pt-2'><ConnectButton /></div>

        <button className='absolute top-4 left-1/2 w-16 h-14 bg-red-500' onClick={()=> playSound()}></button>
        

       
      </main>
      <footer className={styles.footer}>
        have fun 
      </footer>
    </div>
  );
};

export default Home;
